### ISSUE TITLE
When trying to insert items in the machine with enderio's conduits I crash

### ISSUE THREAD

**Issue by Debonairesnake6** [rezonant/rezolve#1]
https://pastebin.com/drajMBhj

**Comment by rezonant** [comment]
Having trouble reproducing a crash, what block were you piping items into, and what items did you pipe into it?

**Comment by rezonant** [comment]
Details from CurseForge:
>  I believe it was into the bundler on the top with 7 experience orbs from actually additions, and the drill from actually additions with a single speed upgrade from a standard vanilla chest. Also im wanting to get into modding and am experienced in java, if you would like help let me know

**Comment by rezonant** [comment]
Turns out its a bad idea to implement IItemHandler on your TileEntity if you also implement IInventory, because IItemHandler does not get obfuscated, so the getStackInSlot() method has to be simultaneously not obfuscated and also obfuscated for it to work. Since Forge is naturally going to obfuscate your getStackInSlot() method, the IItemHandler interface is the one that gets left without an implementation for this method, and Java sees the object as not implementing the method of IItemHandler, hence the AbstractMethodError. 

@Debonairesnake6 Please grab the build at https://packagecloud.io/rezonant/rezolve/packages/java/Rezolve-1.10.2-1.1.24.jar/artifacts/Rezolve-1.10.2-1.1.24.jar/download
... and let me know if you still get the issue.

Cheers!
